//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BENGKEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerVehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerVehicle()
        {
            this.DetailTrxes = new HashSet<DetailTrx>();
        }
    
        public int CustomerVehicleId { get; set; }
        public string CustomerId { get; set; }
        public string VehicleId { get; set; }
        public string Number { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTrx> DetailTrxes { get; set; }
    }
}
