//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BENGKEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTrx
    {
        public int DetailTrxId { get; set; }
        public string TrxId { get; set; }
        public int CustomerVehicleId { get; set; }
        public int Cost { get; set; }
    
        public virtual CustomerVehicle CustomerVehicle { get; set; }
        public virtual HeaderTrx HeaderTrx { get; set; }
    }
}
