//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BENGKEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db : DbContext
    {
        public db()
            : base("name=db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerVehicle> CustomerVehicles { get; set; }
        public virtual DbSet<DetailTrx> DetailTrxes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<HeaderTrx> HeaderTrxes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
